server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848 # 修改本机的host文件
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: test_router
          uri: https://www.baidu.com/
          predicates:
            - Path=/test

