server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: st.zeus.cn:8848/ # 修改本机的host文件
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1 # 当前端访问 /admin/login -> login 将admin自动去掉
        - id: test_router
          uri: https://www.aliyun.com/
          predicates:
            - Path=/product

    sentinel:
      transport:
        dashboard: st.zeus.cn:8858
      datasource:
#        ds1.file:
#          file: classpath:gw-flow.json
#          ruleType: gw_flow
        ds1.nacos:
          serverAddr: st.zeus.cn:8848
          dataId: gw-flow
          ruleType: gw_flow

#        ds2.file:
#          file: classpath:api-group.json
#          ruleType: gw_api_group
        ds2.nacos:
          serverAddr: st.zeus.cn:8848
          dataId: api-group
          ruleType: gw_api_group

  redis:
    host: st.zeus.cn
    port: 6380
    password: 123456


