server:
  port: 9999

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: st.zeus.cn:8848
  redis:
    host: st.zeus.cn
    port: 6379
    password: 123456
