server:
  port: 9999

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: st.zeus.cn:8848
  datasource:
    url: jdbc:mysql://st.zeus.cn:3307/coin-exchange?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
